version: '3.7'

# Red que vamos a establecer para los contenedores
networks:
  redv1: #Nombre de la red
    driver: bridge #Tipo de la red
    ipam:
      config:
        - subnet: 172.28.1.0/29 #Subred a la que pertenece
          gateway: 172.28.1.1 #Puerta de enlace

services:
    php:    #Configuración del contenedor de PHP
        build:
            context: ./config/php   #Configuración que se va a utilizar para el despliegue del contenedor (Dockerfile y www.conf)
        ports:
            - 9000:9000     #Mapeo del puerto de php
        volumes:
            - ./web:/srv/www/api     #Volumen creado de un fichero propio para alojar la web y poder trabajar con PHP (Solo lectura por seguridad)
            - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf    #Volumen creado para actualizar la configuración de php unicamente restaurando los contenedores (Solo lectura por seguridad)
        environment:    #Variables de entorno para el correcto funcionamiento del contenedor mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: Admin1234
            # UPLOAD_MAX_FILESIZE: 20M #TO-DO: CAMBIAR SI FALLA
        links:      #Link entre el contenedor de PHP y MySQL
            - db
        networks:
          redv1:    #Red a la que pertenece
            ipv4_address: 172.28.1.2 # Dirección IP estática del contenedor PHP
 
    nginx:      #Configuración del contenedor de nginx
        image: nginx:latest     #Imagen de nginx que vamos a utilizar (:latest -> Última versión)
        ports:
            - 443:443   #Mapeo del puerto para https
            - 80:80     #Mapeo del puerto de http
        volumes:
            - ./web:/srv/www/api     #Volumen creado de un fichero propio para alojar la web
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf     #Volumen creado de un fichero propio para la configuracion del contenedor de nginx, en este caso para la configuración del virtualhost.
            - ./config/nginx/certificados:/etc/nginx/conf.d      #Volumen creado de un fichero propio para la configuracion del contenedor de nginx, en este caso para la configuración de los certificados.
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php   #Contenedor del que depende
        networks:
          redv1:    #Red a la que pertenece
            ipv4_address: 172.28.1.3 # Dirección IP estática del contenedor Nginx
 
    pma:       #Configuración del contenedor de phpmyadmin
        image: phpmyadmin/phpmyadmin:latest   #Imagen de phpmyadmin que vamos a utilizar (:latest -> Última versión)
        environment:    #Variables de entorno que vamos a utilizar 
            PMA_HOST: db
            PMA_PORT: 3306  #Puerto de mysql
            MYSQL_ROOT_PASSWORD: Admin1234 #Contraseña para el usuario root (Situada en el archivo .env)
        ports:
            - 8000:80     #Mapeo del puerto de phpmyadmin
        depends_on:
            - db    #Contenedor del que depende
        links:
            - db:db
        networks:
          redv1:    #Red a la que pertenece
            ipv4_address: 172.28.1.4 # Dirección IP estática del contenedor PMA

    db:     #Configuración del contenedor mysql
        image: mariadb:latest     #Imagen de mysql que vamos a utilizar (:latest -> Última versión)
        ports:
            - 3306:3306   #Mapeo del puerto de mysql
        # command: "mysqld --init-file /data/application/init.sql"    #Comando para la creacion de la base de datos guardada en el archivo indicado
        volumes:
            # - ./data/init.sql:/data/application/init.sql    #Volumen para la base de datos guardada
            - ./data/_data:/var/lib/mysql    
            # - ./data/_data:/var/lib/mysql                    #Volumen para una futura persistencia de datos
        environment:    #Variables de entorno para el uso de la base de datos
            MYSQL_ROOT_PASSWORD: Admin1234
            MYSQL_DATABASE: mydb
            MYSQL_USER: nytt
            MYSQL_PASSWORD: Admin1234
        networks:   #Red a la que pertenece
          redv1:
            ipv4_address: 172.28.1.5 # Dirección IP estática del contenedor MySQL

volumes:
    db_data:
